# Generated by Django 2.2 on 2021-09-23 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('language_type', models.CharField(default='', max_length=20)),
                ('on_hulu', models.BooleanField(default='')),
                ('on_netflix', models.BooleanField(default='')),
                ('on_crunchyroll', models.BooleanField(default='')),
                ('on_funamation', models.BooleanField(default='')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=models.SET('User Deleted'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('anime_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='animes.Anime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
