# Generated by Django 2.2 on 2021-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_anime_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='image',
        ),
        migrations.AddField(
            model_name='anime',
            name='wiki_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
